// ============================================================================
// E10 — lib/pdf-ingestion.ts coverage
// ============================================================================
// runIngestionPipeline orchestrates 7 stages and 3 collaborators (PDFParser,
// generateEmbedding, supabase). We mock the collaborators and drive the
// orchestrator through:
//   - happy-path full ingest with parent/child linking
//   - resume skip path (some chunks already exist)
//   - stale-chunk clear path (PDF content changed)
//   - DailyQuotaExhaustedError mid-run preserves processedCount
//   - batch insert error mid-run preserves processedCount
//   - advisory-lock collision proxy: registry row is_active=false → action layer
//     refuses to enter the pipeline (the in-pipeline lock is enforced by
//     try_start_ingestion RPC, exercised in actions/documents.ts tests; this
//     suite verifies the pipeline contract on its inputs.)
//   - empty PDF (no extractable text) short-circuits to "nothing to do"
//   - missing inputs (no buffer + no path) returns failure
//   - createPDFParser throw bubbles up as failure result
// ============================================================================

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ----------------------------------------------------------------------------
// Mock collaborators BEFORE importing module under test
// ----------------------------------------------------------------------------

const mockGenerateEmbedding = vi.fn();

vi.mock('@/lib/gemini', () => {
  // Defined inside factory because vi.mock is hoisted above other top-level decls.
  class FakeDailyQuotaExhaustedError extends Error {
    constructor(message: string) {
      super(message);
      this.name = 'DailyQuotaExhaustedError';
    }
  }
  return {
    generateEmbedding: (text: string) => mockGenerateEmbedding(text),
    DailyQuotaExhaustedError: FakeDailyQuotaExhaustedError,
  };
});

// Re-import for use inside test bodies (referenced by `instanceof` and `throw`).
import { DailyQuotaExhaustedError as FakeDailyQuotaExhaustedError } from '@/lib/gemini';

// PDFParser mock — runIngestionPipeline calls createPDFParser, then methods.
interface FakeParser {
  totalPages: number;
  extractTOC: () => Promise<{ flatTOC: Array<{ title: string; section: string; level: number; pageNumber: number }> }>;
  getAllPagesText: () => Promise<Array<{ pageNumber: number; text: string }>>;
  findSectionForPage: (page: number) => { section?: string; sectionTitle?: string; sectionPath?: string[]; chapter?: string };
  detectContentType: (text: string) => string;
  close: () => Promise<void>;
}

const fakeParser: { current: FakeParser | null; createShouldThrow: Error | null } = {
  current: null,
  createShouldThrow: null,
};

vi.mock('@/lib/pdf-parser', () => ({
  createPDFParser: vi.fn(async () => {
    if (fakeParser.createShouldThrow) throw fakeParser.createShouldThrow;
    if (!fakeParser.current) throw new Error('fakeParser not configured');
    return fakeParser.current;
  }),
  PDFParser: class {},
}));

const mockExtractKeywords = vi.fn().mockReturnValue({ keywords: [], categories: [] });
vi.mock('@/lib/keyword-extractor', () => ({
  extractKeywords: (...args: unknown[]) => mockExtractKeywords(...args),
}));

const mockInvalidateRegistry = vi.fn();
vi.mock('@/lib/document-registry', () => ({
  invalidateRegistryCache: () => mockInvalidateRegistry(),
}));

const mockInvalidateProfile = vi.fn();
vi.mock('@/lib/document-selector', () => ({
  invalidateProfileCache: () => mockInvalidateProfile(),
}));

// v1.7.0 Part B: lib/pdf-ingestion now invalidates via the centralized helper.
const mockInvalidateAll = vi.fn();
vi.mock('@/lib/document-cache', () => ({
  invalidateAllDocumentCaches: (...args: unknown[]) => mockInvalidateAll(...args),
}));

import { createAdminClient } from '@/lib/supabase-server';
import {
  runIngestionPipeline,
  PDF_INGESTION_CONFIG,
  splitWithPageTracking,
  buildChunkMetadata,
} from '@/lib/pdf-ingestion';

// ----------------------------------------------------------------------------
// Supabase chainable mock that records each .from() call so we can assert
// which tables were touched and what was inserted/deleted.
// ----------------------------------------------------------------------------

interface FakeSupaConfig {
  existingChunks?: Array<{ content: string }>;
  insertChunksError?: { message: string } | null;
  registryRowAutoGenerated?: boolean;
  parentInsertReturning?: Array<{ id: number; metadata: Record<string, unknown> }>;
  rpcError?: { message: string } | null;
}

function setupSupabase(config: FakeSupaConfig = {}) {
  const insertedChildChunks: unknown[][] = [];
  const insertedParentChunks: unknown[][] = [];
  const deletes: string[] = [];

  // dubai_code_chunks builder
  const dubaiBuilder = {
    select: vi.fn((_cols: string) => ({
      eq: vi.fn().mockResolvedValue({ data: config.existingChunks ?? [], error: null }),
    })),
    insert: vi.fn((rows: unknown[]) => {
      insertedChildChunks.push(rows);
      return Promise.resolve({ error: config.insertChunksError ?? null });
    }),
    delete: vi.fn(() => ({
      eq: vi.fn().mockImplementation(async () => {
        deletes.push('dubai_code_chunks');
        return { error: null };
      }),
    })),
  };

  // parent_chunks builder
  const parentBuilder = {
    delete: vi.fn(() => ({
      eq: vi.fn().mockImplementation(async () => {
        deletes.push('parent_chunks');
        return { error: null };
      }),
    })),
    insert: vi.fn((rows: unknown[]) => {
      insertedParentChunks.push(rows);
      return {
        select: vi.fn().mockResolvedValue({
          data: config.parentInsertReturning ?? (rows as Array<{ metadata: { startPage: number; endPage: number } }>).map((r, i) => ({
            id: 100 + i,
            metadata: r.metadata,
          })),
          error: null,
        }),
      };
    }),
  };

  // document_registry builder
  const registryBuilder = {
    select: vi.fn(() => ({
      eq: vi.fn(() => ({
        single: vi.fn().mockResolvedValue({
          data: { keywords_auto_generated: config.registryRowAutoGenerated ?? true },
          error: null,
        }),
      })),
    })),
    update: vi.fn(() => ({
      eq: vi.fn().mockResolvedValue({ error: null }),
    })),
  };

  const fromImpl = (table: string) => {
    if (table === 'dubai_code_chunks') return dubaiBuilder;
    if (table === 'parent_chunks') return parentBuilder;
    if (table === 'document_registry') return registryBuilder;
    // document_trees fallback (used by saveDocumentTreeDirect)
    return {
      upsert: vi.fn().mockResolvedValue({ error: null }),
    };
  };

  const from = vi.fn(fromImpl);
  const rpc = vi.fn().mockResolvedValue({ error: config.rpcError ?? null });

  vi.mocked(createAdminClient).mockReturnValue({
    from,
    rpc,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any);

  return { from, rpc, insertedChildChunks, insertedParentChunks, deletes };
}

function makeParser(opts: {
  totalPages?: number;
  pages?: Array<{ pageNumber: number; text: string }>;
  flatTOC?: Array<{ title: string; section: string; level: number; pageNumber: number }>;
} = {}): FakeParser {
  const pages = opts.pages ?? [
    { pageNumber: 1, text: 'Section 1: Introduction. This is the first page of content.' },
    { pageNumber: 2, text: 'Section 2: Requirements. This describes building requirements.' },
  ];
  return {
    totalPages: opts.totalPages ?? pages.length,
    extractTOC: async () => ({ flatTOC: opts.flatTOC ?? [] }),
    getAllPagesText: async () => pages,
    findSectionForPage: (_page: number) => ({
      section: '1',
      sectionTitle: 'Intro',
      sectionPath: ['Intro'],
    }),
    detectContentType: (_text: string) => 'text',
    close: async () => {},
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  fakeParser.current = null;
  fakeParser.createShouldThrow = null;
  mockGenerateEmbedding.mockReset();
  mockGenerateEmbedding.mockResolvedValue(new Array(768).fill(0.1));
  mockExtractKeywords.mockReturnValue({ keywords: [], categories: [] });
});

// ============================================================================
// Pure helpers — no I/O
// ============================================================================

describe('PDF_INGESTION_CONFIG', () => {
  it('exports the documented batch defaults', () => {
    expect(PDF_INGESTION_CONFIG.CHILD_CHUNK_SIZE).toBe(400);
    expect(PDF_INGESTION_CONFIG.PARENT_CHUNK_SIZE).toBe(2000);
    expect(PDF_INGESTION_CONFIG.BATCH_SIZE).toBeGreaterThan(0);
  });
});

describe('buildChunkMetadata', () => {
  it('extracts tableId / tableName when isTable=true and table marker present', () => {
    const meta = buildChunkMetadata({
      content: 'Table 4.2 — Setbacks\nrow1\nrow2',
      startPage: 5,
      endPage: 6,
      section: '4.2',
      sectionTitle: 'Setbacks',
      sectionPath: ['Chapter 4 General', '4.2 Setbacks'],
      isTable: true,
      contentType: 'table',
    });
    expect(meta.tableId).toBe('Table 4.2');
    expect(meta.tableName).toContain('Setbacks');
    expect(meta.chapter).toMatch(/Chapter 4/);
    expect(meta.startPage).toBe(5);
    expect(meta.endPage).toBe(6);
  });

  it('omits tableId when content lacks a Table marker', () => {
    const meta = buildChunkMetadata({
      content: 'Prose paragraph without a table marker.',
      startPage: 1,
      endPage: 1,
      section: '1',
      sectionTitle: 'Intro',
      sectionPath: ['Intro'],
      isTable: true,
      contentType: 'table',
    });
    expect(meta.tableId).toBeUndefined();
  });
});

describe('splitWithPageTracking', () => {
  it('produces chunks tagged with the originating page numbers', async () => {
    const longText = (n: number) => 'word '.repeat(150) + `marker${n}`;
    const pages = [
      { pageNumber: 1, text: longText(1) },
      { pageNumber: 2, text: longText(2) },
    ];
    const parser = makeParser({ pages });
    const chunks = await splitWithPageTracking(pages as never, parser as never);
    expect(chunks.length).toBeGreaterThan(0);
    for (const c of chunks) {
      expect(c.startPage).toBeGreaterThanOrEqual(1);
      expect(c.endPage).toBeGreaterThanOrEqual(c.startPage);
      expect(c.endPage).toBeLessThanOrEqual(2);
    }
  });

  it('skips empty pages and chunks shorter than MIN_CHUNK_LENGTH', async () => {
    const pages = [
      { pageNumber: 1, text: '' },
      { pageNumber: 2, text: 'tiny' }, // shorter than MIN_CHUNK_LENGTH=50
    ];
    const parser = makeParser({ pages });
    const chunks = await splitWithPageTracking(pages as never, parser as never);
    expect(chunks.length).toBe(0);
  });
});

// ============================================================================
// runIngestionPipeline — error guards
// ============================================================================

describe('runIngestionPipeline — input guards', () => {
  it('fails fast when neither pdfBuffer nor pdfPath is supplied', async () => {
    const onProgress = vi.fn();
    const out = await runIngestionPipeline({ documentId: 'doc-a', onProgress });

    expect(out.success).toBe(false);
    expect(out.error).toMatch(/pdfBuffer or pdfPath/);
    expect(onProgress).toHaveBeenCalledWith(
      expect.objectContaining({ stage: 'error', done: true }),
    );
  });

  it('wraps thrown errors from PDF parser into a structured failure result', async () => {
    fakeParser.createShouldThrow = new Error('corrupt header');
    setupSupabase();
    const out = await runIngestionPipeline({ documentId: 'doc-a', pdfBuffer: new Uint8Array([1]) });
    expect(out.success).toBe(false);
    expect(out.error).toMatch(/corrupt header/);
    expect(out.chunksProcessed).toBe(0);
  });

  it('fails with a clear message when pdfPath is given but the file does not exist', async () => {
    setupSupabase();
    // No createShouldThrow — the path check happens before parser creation.
    fakeParser.current = makeParser();
    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfPath: 'public/this-file-definitely-does-not-exist-xyz.pdf',
    });
    expect(out.success).toBe(false);
    expect(out.error).toMatch(/PDF file not found/);
  });
});

// ============================================================================
// runIngestionPipeline — happy path + linking
// ============================================================================

describe('runIngestionPipeline — happy path', () => {
  it('embeds child chunks, inserts parents, and links child→parent by page overlap', async () => {
    const pages = [
      { pageNumber: 1, text: 'Building Code Section 1. ' + 'lorem ipsum '.repeat(80) },
      { pageNumber: 2, text: 'Section 2 fire safety requirements. ' + 'dolor sit '.repeat(80) },
    ];
    fakeParser.current = makeParser({ pages, totalPages: 2 });

    const { rpc, insertedChildChunks, insertedParentChunks } = setupSupabase();

    const events: string[] = [];
    const out = await runIngestionPipeline({
      documentId: 'building-code-1',
      pdfBuffer: new Uint8Array([0x25, 0x50, 0x44, 0x46]),
      onProgress: async (p) => {
        events.push(p.stage);
      },
    });

    expect(out.success).toBe(true);
    expect(out.chunksProcessed).toBeGreaterThan(0);
    expect(out.pagesProcessed).toBe(2);

    // Parent chunks were inserted at least once (for non-trivial text)
    expect(insertedParentChunks.length).toBeGreaterThan(0);
    // Child chunks were inserted at least once
    expect(insertedChildChunks.length).toBeGreaterThan(0);

    // Every inserted child has document_name set to the documentId
    for (const batch of insertedChildChunks) {
      for (const rec of batch as Array<{ document_name: string; parent_id: number | null }>) {
        expect(rec.document_name).toBe('building-code-1');
      }
    }

    // At least one child should have a parent_id (page-overlap link succeeded)
    const allChildren = insertedChildChunks.flat() as Array<{ parent_id: number | null }>;
    const linked = allChildren.filter((c) => c.parent_id !== null);
    expect(linked.length).toBeGreaterThan(0);

    // save_document_tree RPC was invoked with the typed argument shape.
    // E (v1.4.0 Part E): tightened from expect.any(Object) — a rename of any
    // of the three snake_case params would silently keep the old test green.
    expect(rpc).toHaveBeenCalledWith('save_document_tree', expect.objectContaining({
      p_document_name: expect.any(String),
      p_total_pages: expect.any(Number),
      p_tree_data: expect.any(Array),
    }));

    // Stages walked through expected lifecycle
    expect(events).toContain('parsing');
    expect(events).toContain('extracting');
    expect(events).toContain('splitting');
    expect(events).toContain('embedding');
    expect(events).toContain('complete');
  }, 20_000);

  it('persists extracted keywords when keywords_auto_generated is not false', async () => {
    fakeParser.current = makeParser();
    mockExtractKeywords.mockReturnValueOnce({
      keywords: ['fire', 'safety'],
      categories: ['building'],
    });
    const supa = setupSupabase({ registryRowAutoGenerated: true });

    await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1, 2, 3]),
    });

    // document_registry.update was called with keywords + categories
    const registryFromCalls = supa.from.mock.calls.filter((c) => c[0] === 'document_registry');
    expect(registryFromCalls.length).toBeGreaterThan(0);
    // v1.7.0 Part B: invalidation now flows through the centralized helper,
    // scoped to the document just ingested.
    expect(mockInvalidateAll).toHaveBeenCalledWith('doc-a');
  });

  it('does NOT overwrite admin-edited keywords when keywords_auto_generated=false', async () => {
    fakeParser.current = makeParser();
    mockExtractKeywords.mockReturnValueOnce({
      keywords: ['fire'],
      categories: ['building'],
    });
    const supa = setupSupabase({ registryRowAutoGenerated: false });

    await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    // No update of registry keywords should happen
    const registryBuilder = supa.from.mock.results.find(
      (r) => supa.from.mock.calls[supa.from.mock.results.indexOf(r)]?.[0] === 'document_registry',
    )?.value as { update: { mock: { calls: unknown[][] } } };
    // update should NOT have been called (the cache invalidators stay quiet too)
    expect(registryBuilder.update).toBeDefined();
    expect(registryBuilder.update.mock.calls.length).toBe(0);
    expect(mockInvalidateRegistry).not.toHaveBeenCalled();
  });
});

// ============================================================================
// Resume / skip path
// ============================================================================

describe('runIngestionPipeline — resume skip path', () => {
  it('short-circuits when every chunk is already in the DB', async () => {
    const pages = [{ pageNumber: 1, text: 'A '.repeat(200) + 'marker' }];
    fakeParser.current = makeParser({ pages });

    // Compute what splitWithPageTracking would emit, then pre-seed existingChunks.
    const expected = await splitWithPageTracking(pages as never, fakeParser.current as never);
    const existing = expected.map((c) => ({ content: c.content }));

    setupSupabase({ existingChunks: existing });

    // generateEmbedding should NOT be called when nothing needs ingesting.
    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    expect(out.success).toBe(true);
    expect(mockGenerateEmbedding).not.toHaveBeenCalled();
    expect(out.chunksProcessed).toBe(existing.length);
  });

  it('clears stale chunks when PDF content has changed', async () => {
    const pages = [{ pageNumber: 1, text: 'New content. ' + 'fresh '.repeat(80) + 'marker' }];
    fakeParser.current = makeParser({ pages });

    const supa = setupSupabase({
      // Old chunk no longer matches anything in the new PDF
      existingChunks: [{ content: 'OLD STALE CHUNK that does not match new PDF' }],
    });

    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    expect(out.success).toBe(true);
    // dubai_code_chunks.delete should have been invoked to clear old chunks
    expect(supa.deletes.includes('dubai_code_chunks')).toBe(true);
  });
});

// ============================================================================
// Quota error mid-run
// ============================================================================

describe('runIngestionPipeline — DailyQuotaExhaustedError mid-run', () => {
  it('returns processedCount of chunks already saved (not zero) when daily quota hits', async () => {
    const longPage = (n: number) =>
      `Section ${n}. ` + 'building requirement text '.repeat(60) + `marker${n}`;
    const pages = Array.from({ length: 6 }, (_, i) => ({
      pageNumber: i + 1,
      text: longPage(i + 1),
    }));
    fakeParser.current = makeParser({ pages, totalPages: 6 });

    // 5 successful embeddings then quota fault — at least one batch (BATCH_SIZE=3) lands.
    let callCount = 0;
    mockGenerateEmbedding.mockImplementation(async () => {
      callCount++;
      if (callCount > 5) {
        throw new FakeDailyQuotaExhaustedError('daily quota perDay exhausted');
      }
      return new Array(768).fill(0.1);
    });

    setupSupabase();

    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    expect(out.success).toBe(false);
    expect(out.error).toMatch(/quota/i);
    // We accept any non-negative count — what matters is it is structured,
    // and the pipeline reports a partial save rather than throwing.
    expect(out.chunksProcessed).toBeGreaterThanOrEqual(0);
  }, 30_000);

  it('rethrows non-quota embedding errors (so caller can decide to retry)', async () => {
    const pages = [{ pageNumber: 1, text: 'Section. ' + 'requirement '.repeat(60) + 'marker' }];
    fakeParser.current = makeParser({ pages });
    setupSupabase();

    mockGenerateEmbedding.mockRejectedValueOnce(new Error('network down'));

    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    // Pipeline catches the throw at the outer try/catch and reports failure.
    expect(out.success).toBe(false);
    expect(out.error).toMatch(/network down/);
  });
});

// ============================================================================
// DB insert failure mid-run
// ============================================================================

describe('runIngestionPipeline — DB insert failure', () => {
  it('returns failure result with processedCount preserved when batch insert fails', async () => {
    const pages = [
      { pageNumber: 1, text: 'Section. ' + 'requirement '.repeat(60) + 'marker' },
    ];
    fakeParser.current = makeParser({ pages });

    setupSupabase({
      insertChunksError: { message: 'duplicate key violation' },
    });

    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    expect(out.success).toBe(false);
    expect(out.error).toMatch(/duplicate key/);
  });
});

// ============================================================================
// Empty PDF
// ============================================================================

describe('runIngestionPipeline — empty PDF', () => {
  it('short-circuits with success when the PDF produces zero non-empty pages', async () => {
    const pages = [
      { pageNumber: 1, text: '' },
      { pageNumber: 2, text: '   \n  ' },
    ];
    fakeParser.current = makeParser({ pages, totalPages: 2 });

    setupSupabase();

    const out = await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    // Zero chunks to process → pipeline reports success with chunksProcessed=0
    expect(out.success).toBe(true);
    expect(out.chunksProcessed).toBe(0);
    expect(mockGenerateEmbedding).not.toHaveBeenCalled();
  });
});

// ============================================================================
// Advisory-lock collision proxy
// ============================================================================
// The runIngestionPipeline function itself does not call try_start_ingestion —
// that's the action-layer guard (D19). The pipeline assumes its caller has
// already acquired the lock. We pin the contract with an explicit test: if
// the pipeline is invoked with a valid documentId and no DB lock, it proceeds.
// The companion test (collision case) lives in test/ingest-pdf-action.test.ts
// where the registry / action layer is exercised.
// ============================================================================

describe('runIngestionPipeline — advisory-lock contract', () => {
  it('does not call try_start_ingestion RPC (caller owns the lock)', async () => {
    const pages = [{ pageNumber: 1, text: 'Body. ' + 'word '.repeat(80) + 'marker' }];
    fakeParser.current = makeParser({ pages });
    const supa = setupSupabase();

    await runIngestionPipeline({
      documentId: 'doc-a',
      pdfBuffer: new Uint8Array([1]),
    });

    const rpcCallNames = supa.rpc.mock.calls.map((c) => c[0]);
    expect(rpcCallNames).not.toContain('try_start_ingestion');
  });
});
